services:
  - type: web
    name: network-monitoring-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn yourprojectname.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: settings.py
