services:
  - type: web
    name: network-monitoring-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn networkmonitor.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: settings.py
